
LOGIN_LINK_ID = "login_link"
EMAIL_REGISTRATION_FIELD_ID = "id_registration-email"
PASSWORD_REGISTRATION_FIELD_ID = "id_registration-password1"
PASSWORD_CONFIRM_REGISTRATION_FIELD_ID = "id_registration-password2"
REGISTRATION_BUTTON_NAME = "registration_submit"
CONFIRM_REGISTRATION_ALERT_NAME = "alert-success"
BOOKS_ITEM_NAVIGATION_MENU_CLASS = "dropdown-submenu"
CODERS_WORK_BOOK_TITLE_CSS = "[title='Coders at Work']"
ADD_BUSKET_BUTTON_ID = "add_to_basket_form"
